name = "cuNumeric"
uuid = "0fd9ffd4-7e84-4cd0-b8f8-645bd8c73620"
version = "25.5.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
CUTENSOR_jll = "35b6c64b-1ee1-5834-92a3-3f624899209a"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
Legate = "1238f2cf-6593-4d60-9aca-2f5364e49909"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCCL_jll = "4d6d38e4-5b87-5e63-912a-873ff2d649b7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
CxxWrap = "0.17"
julia = "1.10"
