name = "cuNumeric"
uuid = "0fd9ffd4-7e84-4cd0-b8f8-645bd8c73620"
authors = ["ejmeitz <emeitz@andrew.cmu.edu>"]
version = "0.0.1"

[deps]
CNPreferences = "b1a454a6-5b08-49bf-9077-82f139a6b048"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[sources]
CNPreferences = {url = "https://github.com/ejmeitz/CNPreferences.jl"}


[compat]
CxxWrap = "0.16"
julia = "1.10"
